language: r
sudo: false
script: make bacon
cache: packages

r_packages:
  - rmarkdown

os:
  - linux

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
