language: r
sudo: false
script: make bacon
cache: packages

r_github_packages:
  - hadley/devtools@efa894ffa

r_packages:
  - rmarkdown
  - ggplot2

os:
  - linux

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
